server:
  host: "0.0.0.0"
  port: 8080
  timeout:
    read: 5s
    write: 10s
    idle: 15s

database:
  host: "postgres"
  port: 5432
  user: "bwadmin"
  password: "bwpassword"
  dbname: "idp_db"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0
  pool_size: 10

auth:
  jwt:
    secret_key: "your-secret-key-here"
    expiration: "24h"
    refresh_expiration: "168h"
  password:
    min_length: 8
    require_uppercase: true
    require_number: true
    require_special: true

logging:
  level: "debug"
  format: "json"

cors:
  allowed_origins:
    - "http://localhost:3000"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Authorization"
    - "Content-Type"
  max_age: 86400

monitoring:
  metrics_path: "/metrics"
  health_check_path: "/health"